# Generated by Django 3.1 on 2020-08-18 17:53

from django.db import migrations, models

import shortify.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortenedURL",
            fields=[
                (
                    "short_path",
                    models.CharField(
                        default=shortify.utils.gen_short_path,
                        max_length=6,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(max_length=8190)),
            ],
        ),
    ]
