# Generated by Django 3.1 on 2020-08-19 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortify", "0003_shortenedurl_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Click",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("ip", models.GenericIPAddressField(null=True)),
                ("http_referer", models.URLField(max_length=2048, null=True)),
                (
                    "shortened_url",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="shortify.shortenedurl"
                    ),
                ),
            ],
        ),
    ]
