# Generated by Django 3.1 on 2020-08-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortify", "0004_click"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortenedurl", name="deactivate_at", field=models.DateTimeField(null=True),
        ),
    ]
