# Generated by Django 3.1 on 2020-08-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortify", "0005_shortenedurl_deactivate_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortenedurl",
            name="max_clicks",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="shortenedurl",
            name="number_of_clicks",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
