# Generated by Django 3.1 on 2020-08-23 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shortify", "0007_shortenedurl_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="shortenedurl", name="number_of_clicks",),
    ]
