# Generated by Django 3.1 on 2020-08-23 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortify", "0008_remove_shortenedurl_number_of_clicks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shortenedurl",
            name="deactivate_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shortenedurl",
            name="max_clicks",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
