# Generated by Django 3.1 on 2020-08-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortify", "0009_auto_20200823_2238"),
    ]

    operations = [
        migrations.AddField(
            model_name="shortenedurl",
            name="number_of_clicks",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
